-- ============================================================
-- 006_secondary_muscles.sql
-- Sin sentencias a propósito.
--
-- Antes poblaba secondary_muscles de los 25 ejercicios del seed, pero en una
-- BD vacía las migraciones corren antes que los seeds y no había ejercicios
-- que actualizar. Esos datos viven ahora en el seed 001_seed_exercises.sql.
-- El fichero se conserva para que el número 006 siga registrado en
-- schema_migrations en las BD donde ya se aplicó.
-- ============================================================
