// Catálogo real de ejercicios (seeds 001 + 004) para tests de emparejado.
// [nombre, categoría, grupo muscular]
export const CATALOG_FIXTURE: [string, string, string][] = [
  ["90/90 Hip Stretch","flexibility","legs"],
  ["Ab Wheel (Rueda Abdominal)","strength","core"],
  ["Abducción de Cadera en Máquina","strength","legs"],
  ["Aducción de Cadera en Máquina","strength","legs"],
  ["Ankle Circles","flexibility","legs"],
  ["Aperturas Inclinadas con Mancuernas","strength","chest"],
  ["Aperturas con Mancuernas","strength","chest"],
  ["Assault Bike","cardio","full_body"],
  ["Battle Ropes","hiit","full_body"],
  ["Belt Squat","strength","legs"],
  ["Bicicleta Estática","cardio","legs"],
  ["Box Jumps","hiit","legs"],
  ["Broad Jump","hiit","legs"],
  ["Burpees","cardio","full_body"],
  ["Cable Crunch","strength","core"],
  ["Carrera en Cinta","cardio","full_body"],
  ["Cat-Cow","flexibility","back"],
  ["Child's Pose","flexibility","back"],
  ["Chin-Up (Dominada Supina)","strength","back"],
  ["Clamshell con Banda","strength","legs"],
  ["Clean con Barra","strength","full_body"],
  ["Couch Stretch","flexibility","legs"],
  ["Crossover en Polea","strength","chest"],
  ["Crunch en Máquina","strength","core"],
  ["Curl Araña (Spider Curl)","strength","arms"],
  ["Curl Bayesian","strength","arms"],
  ["Curl Concentrado","strength","arms"],
  ["Curl Inclinado en Banco","strength","arms"],
  ["Curl Martillo","strength","arms"],
  ["Curl con Barra EZ","strength","arms"],
  ["Curl con Mancuerna","strength","arms"],
  ["Curl de Bíceps con Barra","strength","arms"],
  ["Curl en Banco Predicador con Mancuerna","strength","arms"],
  ["Curl en Banco Predicador","strength","arms"],
  ["Curl en Polea Baja","strength","arms"],
  ["Dead Bug","strength","core"],
  ["Deep Squat Hold","flexibility","legs"],
  ["Depth Jump","hiit","legs"],
  ["Dominadas","strength","back"],
  ["Doorway Chest Stretch","flexibility","chest"],
  ["Dragon Flag","strength","core"],
  ["Elevaciones Frontales con Disco","strength","shoulders"],
  ["Elevaciones Frontales con Mancuernas","strength","shoulders"],
  ["Elevaciones Laterales con Mancuernas","strength","shoulders"],
  ["Elevaciones Laterales en Polea","strength","shoulders"],
  ["Elevación de Gemelos Sentado","strength","legs"],
  ["Elevación de Gemelos de Pie","strength","legs"],
  ["Elevación de Gemelos en Prensa","strength","legs"],
  ["Encogimientos de Hombros con Barra","strength","back"],
  ["Encogimientos de Hombros con Mancuernas","strength","back"],
  ["Escaladora (Stepmill)","cardio","legs"],
  ["Estiramiento de Cuádriceps de Pie","flexibility","legs"],
  ["Estiramiento de Gemelos en Pared","flexibility","legs"],
  ["Estiramiento de Isquiotibiales","flexibility","legs"],
  ["Extensión de Cuádriceps en Máquina","strength","legs"],
  ["Extensión de Tríceps Trasnuca con Mancuerna","strength","arms"],
  ["Extensión de Tríceps Trasnuca en Polea","strength","arms"],
  ["Extensión de Tríceps en Polea (Barra)","strength","arms"],
  ["Extensión de Tríceps en Polea (Cuerda)","strength","arms"],
  ["Face Pull","strength","shoulders"],
  ["Farmer's Carry","strength","core"],
  ["Farmer's Walk","strength","full_body"],
  ["Femoral en Máquina Sentado","strength","legs"],
  ["Femoral en Máquina Tumbado","strength","legs"],
  ["Flexiones Diamante","strength","chest"],
  ["Flexiones con Pies Elevados","strength","chest"],
  ["Flexiones","strength","chest"],
  ["Fondos en Banco","strength","arms"],
  ["Fondos en Paralelas","strength","chest"],
  ["Frog Stretch","flexibility","legs"],
  ["Glute Bridge","strength","legs"],
  ["Good Morning","strength","back"],
  ["Hack Squat","strength","legs"],
  ["Hanging Leg Raise","strength","core"],
  ["Hip Flexor Stretch","flexibility","legs"],
  ["Hip Thrust con Barra","strength","legs"],
  ["Hip Thrust en Máquina","strength","legs"],
  ["Hiperextensión en Banco Romano","strength","back"],
  ["Hollow Body Hold","strength","core"],
  ["Jalón al Pecho Agarre Abierto","strength","back"],
  ["Jalón al Pecho Agarre Cerrado","strength","back"],
  ["Jalón al Pecho Agarre Neutro","strength","back"],
  ["Jumping Jacks","cardio","full_body"],
  ["Kettlebell Swings","hiit","full_body"],
  ["Kickback de Tríceps","strength","arms"],
  ["L-Sit","strength","core"],
  ["Lat Stretch en Polea","flexibility","back"],
  ["Lateral Bound","hiit","legs"],
  ["Mountain Climbers","cardio","core"],
  ["Neck Circles","flexibility","full_body"],
  ["Nordic Curl","strength","legs"],
  ["Pallof Press","strength","core"],
  ["Patada de Glúteo en Polea","strength","legs"],
  ["Peck Deck","strength","chest"],
  ["Peso Muerto Rumano","strength","legs"],
  ["Peso Muerto Sumo","strength","legs"],
  ["Peso Muerto","strength","back"],
  ["Pigeon Pose","flexibility","legs"],
  ["Pistol Squat","balance","legs"],
  ["Plancha (Plank)","strength","core"],
  ["Plancha Lateral","strength","core"],
  ["Prensa de Piernas","strength","legs"],
  ["Press Arnold","strength","shoulders"],
  ["Press Francés (Skull Crusher)","strength","arms"],
  ["Press Francés con Mancuernas","strength","arms"],
  ["Press Inclinado con Mancuernas","strength","chest"],
  ["Press Militar","strength","shoulders"],
  ["Press con Mancuernas (Hombro)","strength","shoulders"],
  ["Press de Banca Agarre Cerrado","strength","arms"],
  ["Press de Banca Declinado con Barra","strength","chest"],
  ["Press de Banca Inclinado con Barra","strength","chest"],
  ["Press de Banca con Mancuernas","strength","chest"],
  ["Press de Banca","strength","chest"],
  ["Press en Máquina (Chest Press)","strength","chest"],
  ["Press en Máquina (Shoulder Press)","strength","shoulders"],
  ["Pullover con Mancuerna","strength","chest"],
  ["Pullover en Polea","strength","chest"],
  ["Push Press","strength","shoulders"],
  ["Pushdown en Polea (Barra V)","strength","arms"],
  ["Rack Pull","strength","back"],
  ["Remo Gironda Agarre Abierto","strength","back"],
  ["Remo Gironda Unilateral","strength","back"],
  ["Remo T","strength","back"],
  ["Remo al Mentón","strength","shoulders"],
  ["Remo con Barra","strength","back"],
  ["Remo con Mancuerna Unilateral","strength","back"],
  ["Remo en Ergómetro","cardio","full_body"],
  ["Remo en Máquina Bilateral","strength","back"],
  ["Remo en Máquina Unilateral","strength","back"],
  ["Reverse Flys (Pájaro)","strength","shoulders"],
  ["Reverse Flys en Máquina","strength","shoulders"],
  ["Russian Twist","strength","core"],
  ["Saltar a la Comba","cardio","full_body"],
  ["Sentadilla Búlgara","strength","legs"],
  ["Sentadilla Goblet","strength","legs"],
  ["Sentadilla con Barra","strength","legs"],
  ["Sentadilla con Salto","hiit","legs"],
  ["Shoulder Dislocates","flexibility","shoulders"],
  ["Single Leg Deadlift","balance","legs"],
  ["Sit-Up en Banco Declinado","strength","core"],
  ["Skipping (Rodillas Altas)","cardio","legs"],
  ["Sled Push","strength","legs"],
  ["Snatch con Kettlebell","strength","full_body"],
  ["Sprints 20 metros","hiit","legs"],
  ["Step-Up con Mancuernas","strength","legs"],
  ["Suitcase Carry","strength","core"],
  ["Thoracic Rotation","flexibility","back"],
  ["Thread the Needle","flexibility","back"],
  ["Thrusters con Mancuernas","hiit","full_body"],
  ["Tire Flip","strength","full_body"],
  ["Windshield Wipers","strength","core"],
  ["World's Greatest Stretch","flexibility","full_body"],
  ["YTW Raises","strength","shoulders"],
  ["Zancadas Caminando","strength","legs"],
  ["Zancadas con Mancuernas","strength","legs"],
]
